"""Added storename to Store link

Revision ID: 0585597e5001
Revises: 7c85c5243902
Create Date: 2025-07-12 12:32:23.741429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0585597e5001'
down_revision = '7c85c5243902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storelinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint("uq_storelinks_name", ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storelinks', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_storelinks_name", ['name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
