"""initial migration

Revision ID: 858865e95a45
Revises: 
Create Date: 2025-07-12 11:39:42.921262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858865e95a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chainId', sa.String(), nullable=True),
    sa.Column('subChainId', sa.String(), nullable=True),
    sa.Column('storeId', sa.String(), nullable=True),
    sa.Column('bikoretNo', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ItemCode', sa.String(), nullable=True),
    sa.Column('ItemNm', sa.String(), nullable=False),
    sa.Column('ManufacturerName', sa.String(), nullable=True),
    sa.Column('Quantity', sa.Float(), nullable=True),
    sa.Column('QtyInPackage', sa.Float(), nullable=True),
    sa.Column('ItemPrice', sa.Float(), nullable=False),
    sa.Column('AllowDiscount', sa.Boolean(), nullable=True),
    sa.Column('ItemStatus', sa.Boolean(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk_items_chain_id_chains')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_items_store_id_stores')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('stores')
    op.drop_table('chains')
    # ### end Alembic commands ###
